### PR TITLE
chore(deps): bump pdfjs-dist in order to fix render issues with pdf/a

### PR DESCRIPTION
**Pull request by Skaronator**
This resolves issues I have with displaying a PDF/A file.

More information here: https://github.com/paperless-ngx/paperless-ngx/issues/3743

### CODE REVIEW

**Comment by abhijeetkpawar** [comment]
Any reason for not goint to v3?

**Comment by Skaronator** [comment]
Yes. Basically, it didn't work out of the box, and I have no experience with Angular nor using this libary. You are welcome to submit a PR for v3.

**Comment by shamoon** [comment]
@VadimDez I appreciate you probably have a lot else on your plate but wanted to check in.

I would hope a minor bump to pdf.js would be low risk for breaking but still has some real benefit (many users of a project I work on are hitting this issue). Any chance of getting this merged and a release? Of course I'd be happy to help if there's any way that would be useful

**Comment by nimodius** [comment]
This would be very hepful indeed!

**Comment by VadimDez** [comment]
Closing this one as it's been updated in the latest `10.0.0` version

**Comment by shamoon** [comment]
Awesome thank you!

**Pull request closed without merging**
