### PR TITLE
Update to Angular 14

### PR DESCRIPTION
**Pull request by ODAncona**
I tried:

`npm run test`

and everything seemed to work.

### CODE REVIEW

**Comment by VadimDez** [comment]
I don't know if you've seen that there was already #915 for this

**Comment by ODAncona** [comment]
Indeed, but I'm not sure how to proceed. I just forked the repo, updated to 14 and opened a PR because I saw your was failing. What should I've done?

**Comment by VadimDez** [comment]
First of all thanks for you contribution, I really appreciate it!
I wouldn't recommend tackle the same issue/feature in parallel.
I did assign #914 to myself and was still working on #915 branch (was trying to fix the SSR issue) that's why i didn't commit latest changes 😅

**Comment by ODAncona** [comment]
Should we merge this pull request and open a new one for the ssr problem?

**Pull request closed without merging**
