### PR TITLE
Fixes: PageChange event on singlepage viewer / Feat: Add search results info callbacks

### PR DESCRIPTION
**Pull request by rlesavre**
Fixes PageChange event on singlepage viewer / Added search results info

### CODE REVIEW

**Comment by rlesavre** [comment]
prPdfJsANgular

**Comment by mantuonweb** [comment]
Great thanks foe fixing it

**Comment by rlesavre** [comment]
@VadimDez any chance you have a look at this PR ?

**Comment by rlesavre** [comment]
merged from lastet upstream

**Comment by rlesavre** [comment]
Any chances @VadimDez ?
Thanks

**Comment by rlesavre** [comment]
Merged again from https://github.com/VadimDez/ng2-pdf-viewer @VadimDez

**Comment by rlesavre** [comment]
Are there any improvements to be made to have this PR pulled @VadimDez ?
Many thanks

**Pull request closed without merging**
