### PR TITLE
Feat: Angular 13 Update | Enable Ivy

### PR DESCRIPTION
**Pull request by PhilippSonntagORGADATA**
Hello,

I've got into [an issue](https://github.com/VadimDez/ng2-pdf-viewer/issues/854) that prevented me from using this library in our project. The solution would be to update this library to the new Ivy rendering engine which worked fine in my first tests.

As stated in the [Angular blog](https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49), this is a recommended but not necessary step for most use-cases.

The library along with the material dependencies were updated using the @angular/cli.
I've manually executed the test scripts on my machine and tested it in the latest versions of macOS Safari / FF / Chromium (Brave).

### CODE REVIEW

**Comment by ODAncona** [comment]
Does it solve the issue #846 ?

**Comment by PhilippSonntagORGADATA** [comment]
I'm not entirely sure whether it could fix this issue. But using the updated version of the library works really good in my use-cases with pnpm.

You could try it yourself by replacing the `ng2-pdf-viewer` dependency in the package json with the following:
```
"ng2-pdf-viewer": "github:PhilippSonntagORGADATA/ng2-pdf-viewer#angular-13-update-dist",
```
This branch contains the compiled version of the updated library. You can use it to check if your bugs still appear in an updated version of the library.

**Please note that nobody should use this version for anything but testing purposes. I will delete this fork as soon as this pull request is merged.**

**Review by VadimDez — APPROVED** [review]
Looks good, will make few tests on my own

**Comment by PhilippSonntagORGADATA** [comment]
Can I do something to help you on this or are there any updates? @VadimDez

**Comment by sravan-pallamreddy** [comment]
Please let us know when this can be pushed to the npm repository.

**Pull request merged**
