### PR TITLE
Update to Angular 16

### PR DESCRIPTION
**Pull request by VadimDez**

### CODE REVIEW

**Review by MirceaTheOldMan — APPROVED** [review]

**Comment by SoyDiego** [comment]
Hi @VadimDez, will you update to Angular 16?
Thanks

**Comment by ChristopherVR** [comment]
Hi @VadimDez ,

Any change to update to Angular 16?

**Comment by acosme** [comment]
Hi @VadimDez,

will this commit go to master?

**Comment by naviln** [comment]
Hi @VadimDez,

Thanks for putting this upgrade out. I tried it out on my Angular 15 project, but getting the below error. Any tips/ideas?

image

```
Error: node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:95:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 9 type arguments.

95     static ɵcmp: i0.ɵɵComponentDeclaration<PdfViewerComponent, "pdf-viewer", never, { "src": { "alias": "src"; "required": false; }; "cMapsUrl": { "alias": "c-maps-url"; "required": false; }; "page": { "alias": "page"; "required": false; }; "renderText": { "alias": "render-text"; "required": false; }; "renderTextMode": { "alias": "render-text-mode"; "required": false; }; "originalSize": { "alias": "original-size"; "required": false; }; "showAll": { "alias": "show-all"; "required": false; }; "stickToPage": { "alias": "stick-to-page"; "required": false; }; "zoom": { "alias": "zoom"; "required": false; }; "zoomScale": { "alias": "zoom-scale"; "required": false; }; "rotation": { "alias": "rotation"; "required": false; }; "externalLinkTarget": { "alias": "external-link-target"; "required": false; }; "autoresize": { "alias": "autoresize"; "required": false; }; "fitToPage": { "alias": "fit-to-page"; "required": false; }; "showBorders": { "alias": "show-borders"; "required": false; }; }, { "afterLoadComplete": "after-load-complete"; "pageRendered": "page-rendered"; "pageInitialized": "pages-initialized"; "textLayerRendered": "text-layer-rendered"; "onError": "error"; "onProgress": "on-progress"; "pageChange": "pageChange"; }, never, never, false, never, false>;
```

**Pull request merged**
